[[util_linux]]
arch = "aarch64"
git-tree-sha1 = "47d91f49e6e9a404eb5c2ec281b22cfb2a1e5c0d"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "44b4f9a6a1b465f753ae13fd50ab612e1e615e4e1f2ad181ca8d1adc63a21bff"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.3+0/util_linux.v2.41.3.aarch64-linux-gnu.tar.gz"
[[util_linux]]
arch = "aarch64"
git-tree-sha1 = "28cb8fa9f7a1580a1676dbf328087ed6444f19fb"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "fed22b42abdb4180b91a48f19d6faac5f626c81b2e6cccda83d3fad7fe5485a1"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.3+0/util_linux.v2.41.3.aarch64-linux-musl.tar.gz"
[[util_linux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7f3fac360745ea1acfb484ea6e232cc4e96e921d"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "142051f607f171f6d5a9a0a72b7a143eebb854b427f07187b533dde12f7c6c33"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.3+0/util_linux.v2.41.3.armv6l-linux-gnueabihf.tar.gz"
[[util_linux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "75bc6839e2208c2a8765556ae9ce5a10bde4da6c"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "83c1911176fa33716489873f018caad76ecd94dc41b2b1b62f6311a2934329b2"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.3+0/util_linux.v2.41.3.armv6l-linux-musleabihf.tar.gz"
[[util_linux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c95ea79a870fb6b32cc391faa8b7eef8a4413ac4"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "742a5813232a974f3193ef4d71ff64133ef29ed85435da8d67d795a1117bede0"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.3+0/util_linux.v2.41.3.armv7l-linux-gnueabihf.tar.gz"
[[util_linux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0cdb8dc48862cd38ba68371dbf99845dab8f5162"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "a0519d41abf3c230106d5d110758c1fb5c13d15bf5c821338f78ef002235d3ba"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.3+0/util_linux.v2.41.3.armv7l-linux-musleabihf.tar.gz"
[[util_linux]]
arch = "i686"
git-tree-sha1 = "0625b03990cbff331c4e4841c2c94f0ad30c5bd8"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "81c62f8b330ead16743113877da282c1cace0787406f2a68d2e12d8f312923fd"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.3+0/util_linux.v2.41.3.i686-linux-gnu.tar.gz"
[[util_linux]]
arch = "i686"
git-tree-sha1 = "7c39fd3168e438621ce6a48384a91b4c00e228ef"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "3f9420ebb5250fa20b037e336ac6eac3478fd9a06e82dd7353521fe6bfee5961"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.3+0/util_linux.v2.41.3.i686-linux-musl.tar.gz"
[[util_linux]]
arch = "powerpc64le"
git-tree-sha1 = "ef20f7740972bbbc34f4275654f4487ea835ccb7"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "9a9222923e138f2153633dd430db5ccd16c7445b684b8fbf6715dff994d606de"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.3+0/util_linux.v2.41.3.powerpc64le-linux-gnu.tar.gz"
[[util_linux]]
arch = "riscv64"
git-tree-sha1 = "244bafea392f0b592633c0bdad8998af1a865213"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "c157603c1c65c7918fcaeeb2b26f1c34a51032906ef461137976aa62aa2ac60c"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.3+0/util_linux.v2.41.3.riscv64-linux-gnu.tar.gz"
[[util_linux]]
arch = "x86_64"
git-tree-sha1 = "58dce643213d1131e6c2d46b1d41c487b9eb8b5b"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "40bedf36f8d2b02a18d533f33d462ba60439f1098fdb37846dc8da867095577b"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.3+0/util_linux.v2.41.3.x86_64-linux-gnu.tar.gz"
[[util_linux]]
arch = "x86_64"
git-tree-sha1 = "ca4bee9dd535ed273f8c328f79decdbad07271a4"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "0d8b723a272ff8f97d3cdad1a2b2710b015f4edc8c05c8de0b2e93b19b9a1629"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.3+0/util_linux.v2.41.3.x86_64-linux-musl.tar.gz"
