[[util_linux]]
arch = "aarch64"
git-tree-sha1 = "958e5e79db83bfc6b6205c035788d4c69fbff3ed"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "b19313a1d054f2147242273d650b7b476f135f4e290dea6a952d4ab6862cefc6"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.39.3+0/util_linux.v2.39.3.aarch64-linux-gnu.tar.gz"
[[util_linux]]
arch = "aarch64"
git-tree-sha1 = "ddc9a0a1e877fc96e0ff72dcfb1fe8d6e8288b0e"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "8a6f5ba30de9cd3ac0efbf71af9d0e5f523f8fa50530376c825f67b5a5177e54"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.39.3+0/util_linux.v2.39.3.aarch64-linux-musl.tar.gz"
[[util_linux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "48cee5412507ffdc53b37420afadf81d5cc63c1b"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "a14571f86c90398a9194809222f7c3edd0ce5671ea0d2fcb8c4c45c906a4b19d"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.39.3+0/util_linux.v2.39.3.armv6l-linux-gnueabihf.tar.gz"
[[util_linux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ae5c2c81363b2c9cbd19fdbf38b51faabfd38e46"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "dcd17de52c634796e64e0bcb5d9aa20597203a3b351cb324556f31f462f2efab"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.39.3+0/util_linux.v2.39.3.armv6l-linux-musleabihf.tar.gz"
[[util_linux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b7959801bb82659c613ad722fa7aafc84f51dd35"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "08e4b22f13d405bfb30028ad9302035a70f4ade430c558e3127eb035a28bfb7b"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.39.3+0/util_linux.v2.39.3.armv7l-linux-gnueabihf.tar.gz"
[[util_linux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b78ed2a7dac78e4c7b861f5e48e2986c68bc5c2e"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "4f364c4dfb86520ce4ff251253b3f19d3be2608ae21fc38ffb4ca38a87911193"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.39.3+0/util_linux.v2.39.3.armv7l-linux-musleabihf.tar.gz"
[[util_linux]]
arch = "i686"
git-tree-sha1 = "662fdafc4ea4a3d2ab85578d4a567213674af77c"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "ed8f094f1d7cb8c5811573ea8bbe375777d11ac1e83115e092d8a9709e7b9d9a"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.39.3+0/util_linux.v2.39.3.i686-linux-gnu.tar.gz"
[[util_linux]]
arch = "i686"
git-tree-sha1 = "264e431190d019b092e93aac1cd12f21b7b624af"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "6a1a2febe18c7e577985b22958c5537f061630630cea5da49909f95dca208aec"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.39.3+0/util_linux.v2.39.3.i686-linux-musl.tar.gz"
[[util_linux]]
arch = "powerpc64le"
git-tree-sha1 = "ffa4ad62b2fb1b6b154beae91b5e714a4fca711e"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "3c13f5d4d5fe205b1ec2fd883a7ce5a7d16c8bbf1d4a2c976f04ebcd0fb259a6"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.39.3+0/util_linux.v2.39.3.powerpc64le-linux-gnu.tar.gz"
[[util_linux]]
arch = "x86_64"
git-tree-sha1 = "6328fb722e7059f869d96ae051bf9be27a381b33"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "c83a5c733097119d6ea2327b653c4c3985a1410fde1c3683f3d19db8bdf0aecc"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.39.3+0/util_linux.v2.39.3.x86_64-linux-gnu.tar.gz"
[[util_linux]]
arch = "x86_64"
git-tree-sha1 = "eea1677edeb2f0e975eadd45357103049c2a34e9"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "4f8a62714a6c71a181cf9787256e0aa1dca1b3ad527878e052db6b45082d3799"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.39.3+0/util_linux.v2.39.3.x86_64-linux-musl.tar.gz"
