[[util_linux]]
arch = "aarch64"
git-tree-sha1 = "b3bfe24b73d56da84778f03e026c5f2cf9499a67"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "2d5323c992671785f97e7a97c381f90ee43a3afd3d74f8ddbad7560df702af84"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.42.0+0/util_linux.v2.42.0.aarch64-linux-gnu.tar.gz"
[[util_linux]]
arch = "aarch64"
git-tree-sha1 = "beba36490c5e0f6bfd3c9ae79cf42567e01db213"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "14332b6d2e9bca537e3d4ddc0ad4f6e75001178eee12729cb92f3aa3b819a2fc"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.42.0+0/util_linux.v2.42.0.aarch64-linux-musl.tar.gz"
[[util_linux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f8d8667b702615e4318c5ffbae6e451b1bccfbc2"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "7915b4d67f2f91414c2c0fc7d3ce37562aedfe168b4f70f976701142f85368e3"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.42.0+0/util_linux.v2.42.0.armv6l-linux-gnueabihf.tar.gz"
[[util_linux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4063d26e837d1115f285a8c5e1568c9d4bab3c1e"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "527ebce4597d1bfd334ce7e9b673b3c8541b1807f09a588542764f4e6730c454"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.42.0+0/util_linux.v2.42.0.armv6l-linux-musleabihf.tar.gz"
[[util_linux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fd3a4bb6faaa3072b4585a8cd606ccbd67f235b2"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "1e414042f711f164fe827e9e59dcbf3e355e4dcf40fb5c81a6f22aedd63fa7ea"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.42.0+0/util_linux.v2.42.0.armv7l-linux-gnueabihf.tar.gz"
[[util_linux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d256befce96b49541afebab6ddcbcef584a3d55c"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "6c185aa6072977c1a59e2c2fa204e16c575cbe68e237948dfd52e7d61b7f38e9"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.42.0+0/util_linux.v2.42.0.armv7l-linux-musleabihf.tar.gz"
[[util_linux]]
arch = "i686"
git-tree-sha1 = "fb531f97aa8195033c29c7e5b003ceef7a78415e"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "121643590c511552680d4a477e883ec6ec07c3a23f10219e12a17dd156d17ab6"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.42.0+0/util_linux.v2.42.0.i686-linux-gnu.tar.gz"
[[util_linux]]
arch = "i686"
git-tree-sha1 = "c5d86c720b66ceea4e334769a15f6d2cc7371a1f"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "56877caa8bf7791b06c100b22d00fe828cd0dcb95634d258f80c9b8d1f8fe517"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.42.0+0/util_linux.v2.42.0.i686-linux-musl.tar.gz"
[[util_linux]]
arch = "powerpc64le"
git-tree-sha1 = "fa4b813befcefec6d864cd368bd2dfb0b798ee87"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "8e0e5e77c91c3b4bac9941743149eeee047dabf4b61d413fbebdd0f82bfd316e"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.42.0+0/util_linux.v2.42.0.powerpc64le-linux-gnu.tar.gz"
[[util_linux]]
arch = "riscv64"
git-tree-sha1 = "ce5cb4eaedf38ebdcdc03ae2374a202b4e22b5bb"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "b00e1a1f5946949983a84d3ff7e86b8e18e8e8afa3ba9ae9ee2be7fabb71c92c"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.42.0+0/util_linux.v2.42.0.riscv64-linux-gnu.tar.gz"
[[util_linux]]
arch = "x86_64"
git-tree-sha1 = "be89e46b1f6d230546a1b1d557e735218644f953"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "cc6cca499465df27411434b6cf0f95bcd02b52b2bab3ab611308a339feda297f"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.42.0+0/util_linux.v2.42.0.x86_64-linux-gnu.tar.gz"
[[util_linux]]
arch = "x86_64"
git-tree-sha1 = "9b0b13e9493bdf79cee090ba529687ec38dd6527"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "3f00f365613f9884ea70bf56c83de0d8d85c13a791cbc5abb6ebd01128c5c605"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.42.0+0/util_linux.v2.42.0.x86_64-linux-musl.tar.gz"
