[[util_linux]]
arch = "aarch64"
git-tree-sha1 = "56535f3c01285eea4d5ee3c8aaefc49d28b6a754"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "767f2e7cc920c4152de664985a0a2160a494d90576666c75a1582826b4bd0a47"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.1+0/util_linux.v2.41.1.aarch64-linux-gnu.tar.gz"
[[util_linux]]
arch = "aarch64"
git-tree-sha1 = "1296c93485fe692c0ed2b55731dec72705acb4b7"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "345d0d53184a632b7b14ce9577c089f40541bc7be328505f275c9f51df3e926e"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.1+0/util_linux.v2.41.1.aarch64-linux-musl.tar.gz"
[[util_linux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8504b0284132cce4916f4f0a86fccfd626b55f6a"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "6a80519d24df9cf27d6f0c6e20a4b1d5e15b1f98eae2c90c4e458be820c54ad6"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.1+0/util_linux.v2.41.1.armv6l-linux-gnueabihf.tar.gz"
[[util_linux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "80fd2bfe84ef93292c66c32a1f722f39405fae2a"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "c374b33aa7664a11175f649d1429e998c81f556d0c0edc9b2dd3a7d355425674"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.1+0/util_linux.v2.41.1.armv6l-linux-musleabihf.tar.gz"
[[util_linux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "622d222fd31691a57c21abecf0cc0ac0de9818b0"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "16417d2d87e83d6ebfd8c5ec255e9117ca4ea5158dc994946e5e8ce0245bd3da"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.1+0/util_linux.v2.41.1.armv7l-linux-gnueabihf.tar.gz"
[[util_linux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ea2a994e214a74bd52992358bedbcdfd0e1e0d77"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "cf82ed38fb161a18ac10aa9d3a44269560d99761c4c4669d7b9e7be8afc634c4"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.1+0/util_linux.v2.41.1.armv7l-linux-musleabihf.tar.gz"
[[util_linux]]
arch = "i686"
git-tree-sha1 = "fede1e7926ce7153b3c7ff321c99b03824f97564"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "a7f54ec2b7133c1b577e35f77f17412613e834947e46b04d8e6cb727ccde2afa"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.1+0/util_linux.v2.41.1.i686-linux-gnu.tar.gz"
[[util_linux]]
arch = "i686"
git-tree-sha1 = "31ef3e6d9ccc35a97f56eeadcadf2ffe8ca41d56"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "8feb5acc3a21e8eaa876f45f47e361413c36a7f19a32301f0272fa7d9eaabdf1"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.1+0/util_linux.v2.41.1.i686-linux-musl.tar.gz"
[[util_linux]]
arch = "powerpc64le"
git-tree-sha1 = "102698695cfa5efe33ddc7d56f21750d5091f5bc"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "094ff9868187dcf72e5a169b749fdda0ddaf30c0ce3feec50cd09540962a40ac"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.1+0/util_linux.v2.41.1.powerpc64le-linux-gnu.tar.gz"
[[util_linux]]
arch = "riscv64"
git-tree-sha1 = "66c17a992b46f8276ac2e376acf2a5d0e76e3e59"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "9c3c786d975c6732ec6756199414311e30677e2148c57a3aceca363171d1bdbf"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.1+0/util_linux.v2.41.1.riscv64-linux-gnu.tar.gz"
[[util_linux]]
arch = "x86_64"
git-tree-sha1 = "4e788189ff95e594f783f9e11b89a0ddf7fcc0ec"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "b18e8b055327f4876c20b46942b4542c6b4130b826e296e03015a7ea55679c1e"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.1+0/util_linux.v2.41.1.x86_64-linux-gnu.tar.gz"
[[util_linux]]
arch = "x86_64"
git-tree-sha1 = "d9250d78cf892001447a0c76b769d3a65d6ed1e8"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "c4443b6911eeac18051d5e6cd01609154fffae7c6b554d7bcd44c52cc3c497ca"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.1+0/util_linux.v2.41.1.x86_64-linux-musl.tar.gz"
