[[util_linux]]
arch = "aarch64"
git-tree-sha1 = "164eee924fd52f19a42470ad26030b0fc9ace0f7"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "7d6e897dce4fd1f063e48cf55cff5bf4987982b7e1805035ffa32510a1d34041"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.2+0/util_linux.v2.41.2.aarch64-linux-gnu.tar.gz"
[[util_linux]]
arch = "aarch64"
git-tree-sha1 = "9426da0cd182a6bda3c85237841e2a16038ce20e"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "ba87a50c95d70efead5c8346951a594951b1eeffac86f1589a14da2e789bc694"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.2+0/util_linux.v2.41.2.aarch64-linux-musl.tar.gz"
[[util_linux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e4ab6d293d0c9129edfaa4d0a8f0670905f3fd68"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "77bc455eb239823118ffbeb0e91c154092425a0d7cd3e6c0b787d31dae083073"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.2+0/util_linux.v2.41.2.armv6l-linux-gnueabihf.tar.gz"
[[util_linux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "95456c1b7bac64c58452a24b4d3ab2df1dc6c9e1"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "4921e7518e233d4b27fbbc9cc874f9a7fb879a733dae12ce4eac79b0331dd593"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.2+0/util_linux.v2.41.2.armv6l-linux-musleabihf.tar.gz"
[[util_linux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a4e3769de7d3c96f3331df64b36f59a0863fa2a7"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "862e96a20a9be47e1108e776d3d99b596c62cb7eb4ce88fc4e09064ad6ec95ff"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.2+0/util_linux.v2.41.2.armv7l-linux-gnueabihf.tar.gz"
[[util_linux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a7dad6c1c2d934d7984e863f0fa6e468e78a25b9"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "01f1057711b00a67d602b5e2592fc872005a58101afd154318f8172f9ee76518"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.2+0/util_linux.v2.41.2.armv7l-linux-musleabihf.tar.gz"
[[util_linux]]
arch = "i686"
git-tree-sha1 = "77a683707b75fb841cbd9f3406d94f04b4ec0ad5"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "91e194337b18f75b164f7c656b439ca4bc56b0548b3a5bf26cff7ec09d55186c"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.2+0/util_linux.v2.41.2.i686-linux-gnu.tar.gz"
[[util_linux]]
arch = "i686"
git-tree-sha1 = "905b2ce3dcb9237c6bfd32c849be929a96c571d0"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "1a5d97bfcb6b8ac16d4e3b5fd811dd3ca54040f1d6c3c0d03b069060bd9aa2c4"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.2+0/util_linux.v2.41.2.i686-linux-musl.tar.gz"
[[util_linux]]
arch = "powerpc64le"
git-tree-sha1 = "6fa4ea2d4b0e9a2fddb7551e9330fd7f1865023f"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "84f95dd645580fc1a2e8e118ddd92cf2cc933056d231a23ac2c5e8774252be58"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.2+0/util_linux.v2.41.2.powerpc64le-linux-gnu.tar.gz"
[[util_linux]]
arch = "riscv64"
git-tree-sha1 = "6fb63e7d67e48ba8d2bd557a041552d5940f6fde"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "be64e0d8fd81a24064de7dace80d58e9df3c9fd17aa7aea0f49eec9336599bb4"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.2+0/util_linux.v2.41.2.riscv64-linux-gnu.tar.gz"
[[util_linux]]
arch = "x86_64"
git-tree-sha1 = "2d891205ff8d746546ac514bce2bece91bfa4f70"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "26dbcbe29abc686c3e9eddfa85e19d84e8c28af8b29b14404a5328b482d2f1a7"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.2+0/util_linux.v2.41.2.x86_64-linux-gnu.tar.gz"
[[util_linux]]
arch = "x86_64"
git-tree-sha1 = "8f66bdd991aed42a467f37ad7bfdfeb9bd2d5d68"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "2ca6f306591fef034f0a48ce5e91debf073a401156f80bdc3887dfa6b974c6e8"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.41.2+0/util_linux.v2.41.2.x86_64-linux-musl.tar.gz"
