[[util_linux]]
arch = "aarch64"
git-tree-sha1 = "05fac6c1b6ec739e42081ba87920467c9f029888"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "1a95832778a3fdca74229046114c698d7850d0c8c3ed8f929fffdefa6bd75a47"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.40.2+0/util_linux.v2.40.2.aarch64-linux-gnu.tar.gz"
[[util_linux]]
arch = "aarch64"
git-tree-sha1 = "333ed72bbd5bcfa5c8711a04e0cc0613ae80541b"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "efe021a132b425f99317f7388618c1abcb91f4afed129a0466bfc06dcb10633d"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.40.2+0/util_linux.v2.40.2.aarch64-linux-musl.tar.gz"
[[util_linux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9b957bbfae0c1850ce5a6d8b243a822e22550b16"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "e527f9870e6e1d733f28ff1fc78931b06512e84c98d46b946a345445dab4c146"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.40.2+0/util_linux.v2.40.2.armv6l-linux-gnueabihf.tar.gz"
[[util_linux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fe69641f3b9e6c65565a6fb49ae4e8442ca6976f"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "b21a7ce861757542f4ff2b4ef719e41bac097fe2f3153b654eb53b3b5250910f"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.40.2+0/util_linux.v2.40.2.armv6l-linux-musleabihf.tar.gz"
[[util_linux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3d15d4957701d14d55a25f2e25e249c840cd84c0"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "dc39c568820e766b45c38be5d00b96e50f573debf3a05a24bc4f6178bb20b3ef"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.40.2+0/util_linux.v2.40.2.armv7l-linux-gnueabihf.tar.gz"
[[util_linux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2d0140d00cae94fda0a1315492ef87f192ad85f6"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "444bb65a619f5c2731515536e2de07c59afb48e36fdd5dd9925fba515e933fa1"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.40.2+0/util_linux.v2.40.2.armv7l-linux-musleabihf.tar.gz"
[[util_linux]]
arch = "i686"
git-tree-sha1 = "b489ea59a4dffe928c491fa76f00cc34237d0634"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "aa5bdb83629ca338756cd57ef9741103e36a2332a73060dd3d5785deb3284a4a"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.40.2+0/util_linux.v2.40.2.i686-linux-gnu.tar.gz"
[[util_linux]]
arch = "i686"
git-tree-sha1 = "2ebfa326f7ba0bb5ac65e6b1a59abc958f82e75b"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "b376e1aceafd10b08aca49aba166f53e5b95cf8edefbaa88f36a7266b0c974bd"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.40.2+0/util_linux.v2.40.2.i686-linux-musl.tar.gz"
[[util_linux]]
arch = "powerpc64le"
git-tree-sha1 = "b268628d81cd9f43c7652cb41f34f047330dfa6b"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "6f6bdd207f040ee78e2dbb53a90e8c98690e660936bf0981bc3077a51e6ea5f1"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.40.2+0/util_linux.v2.40.2.powerpc64le-linux-gnu.tar.gz"
[[util_linux]]
arch = "x86_64"
git-tree-sha1 = "cf11733cffadbd52c61b93a76d07c5ed1550a78a"
libc = "glibc"
os = "linux"

    [[util_linux.download]]
    sha256 = "1c7d04158927588918151a9424960a111177ce8e19be7a2436ef06f81e23a978"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.40.2+0/util_linux.v2.40.2.x86_64-linux-gnu.tar.gz"
[[util_linux]]
arch = "x86_64"
git-tree-sha1 = "2d6eb8b808e001216659031d87a2f1a6bf5260ef"
libc = "musl"
os = "linux"

    [[util_linux.download]]
    sha256 = "4b26b2e86e811966967e83136790e81290998eb8be48a3a4237092672c0d8a3e"
    url = "https://github.com/JuliaBinaryWrappers/util_linux_jll.jl/releases/download/util_linux-v2.40.2+0/util_linux.v2.40.2.x86_64-linux-musl.tar.gz"
