# Autogenerated wrapper script for util_linux_jll for riscv64-linux-gnu
export addpart, agetty, blkdiscard, blkid, blkzone, blockdev, cal, chcpu, chmem, choom, chrt, colcrt, colrm, column, ctrlaltdel, delpart, dmesg, eject, enosys, exch, fallocate, fdformat, fdisk, fincore, findfs, findmnt, flock, fsck, fsck_cramfs, fsck_minix, fsfreeze, fstrim, getopt, hardlink, hexdump, hwclock, ionice, ipcmk, ipcrm, ipcs, isosize, kill_bin, last_bin, lastlog2, ldattach, libblkid, libfdisk, liblastlog2, libmount, libsmartcols, libuuid, logger, look, losetup, lsblk, lsclocks, lscpu, lsipc, lslocks, lslogins, lsmem, lsns, mcookie, mesg, mkfs, mkfs_bfs, mkfs_cramfs, mkfs_minix, mkswap, mount, mountpoint, namei, nologin, nsenter, partx, pivot_root, prlimit, raw, readprofile, rename_bin, renice, resizepart, rev, rfkill, rtcwake, script, scriptlive, scriptreplay, setarch, setpgid, setsid, sfdisk, sulogin, swaplabel, swapoff, swapon, switch_root, taskset, umount, unshare, utmpdump, uuidd, uuidgen, uuidparse, wall, wdctl, whereis, wipefs, zramctl

using SQLite_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("util_linux")
JLLWrappers.@declare_library_product(libblkid, "libblkid.so.1")
JLLWrappers.@declare_library_product(libfdisk, "libfdisk.so.1")
JLLWrappers.@declare_library_product(liblastlog2, "liblastlog2.so.2")
JLLWrappers.@declare_library_product(libmount, "libmount.so.1")
JLLWrappers.@declare_library_product(libsmartcols, "libsmartcols.so.1")
JLLWrappers.@declare_library_product(libuuid, "libuuid.so.1")
JLLWrappers.@declare_executable_product(addpart)
JLLWrappers.@declare_executable_product(agetty)
JLLWrappers.@declare_executable_product(blkdiscard)
JLLWrappers.@declare_executable_product(blkid)
JLLWrappers.@declare_executable_product(blkzone)
JLLWrappers.@declare_executable_product(blockdev)
JLLWrappers.@declare_executable_product(cal)
JLLWrappers.@declare_executable_product(chcpu)
JLLWrappers.@declare_executable_product(chmem)
JLLWrappers.@declare_executable_product(choom)
JLLWrappers.@declare_executable_product(chrt)
JLLWrappers.@declare_executable_product(colcrt)
JLLWrappers.@declare_executable_product(colrm)
JLLWrappers.@declare_executable_product(column)
JLLWrappers.@declare_executable_product(ctrlaltdel)
JLLWrappers.@declare_executable_product(delpart)
JLLWrappers.@declare_executable_product(dmesg)
JLLWrappers.@declare_executable_product(eject)
JLLWrappers.@declare_executable_product(enosys)
JLLWrappers.@declare_executable_product(exch)
JLLWrappers.@declare_executable_product(fallocate)
JLLWrappers.@declare_executable_product(fdformat)
JLLWrappers.@declare_executable_product(fdisk)
JLLWrappers.@declare_executable_product(fincore)
JLLWrappers.@declare_executable_product(findfs)
JLLWrappers.@declare_executable_product(findmnt)
JLLWrappers.@declare_executable_product(flock)
JLLWrappers.@declare_executable_product(fsck)
JLLWrappers.@declare_executable_product(fsck_cramfs)
JLLWrappers.@declare_executable_product(fsck_minix)
JLLWrappers.@declare_executable_product(fsfreeze)
JLLWrappers.@declare_executable_product(fstrim)
JLLWrappers.@declare_executable_product(getopt)
JLLWrappers.@declare_executable_product(hardlink)
JLLWrappers.@declare_executable_product(hexdump)
JLLWrappers.@declare_executable_product(hwclock)
JLLWrappers.@declare_executable_product(ionice)
JLLWrappers.@declare_executable_product(ipcmk)
JLLWrappers.@declare_executable_product(ipcrm)
JLLWrappers.@declare_executable_product(ipcs)
JLLWrappers.@declare_executable_product(isosize)
JLLWrappers.@declare_executable_product(kill_bin)
JLLWrappers.@declare_executable_product(last_bin)
JLLWrappers.@declare_executable_product(lastlog2)
JLLWrappers.@declare_executable_product(ldattach)
JLLWrappers.@declare_executable_product(logger)
JLLWrappers.@declare_executable_product(look)
JLLWrappers.@declare_executable_product(losetup)
JLLWrappers.@declare_executable_product(lsblk)
JLLWrappers.@declare_executable_product(lsclocks)
JLLWrappers.@declare_executable_product(lscpu)
JLLWrappers.@declare_executable_product(lsipc)
JLLWrappers.@declare_executable_product(lslocks)
JLLWrappers.@declare_executable_product(lslogins)
JLLWrappers.@declare_executable_product(lsmem)
JLLWrappers.@declare_executable_product(lsns)
JLLWrappers.@declare_executable_product(mcookie)
JLLWrappers.@declare_executable_product(mesg)
JLLWrappers.@declare_executable_product(mkfs)
JLLWrappers.@declare_executable_product(mkfs_bfs)
JLLWrappers.@declare_executable_product(mkfs_cramfs)
JLLWrappers.@declare_executable_product(mkfs_minix)
JLLWrappers.@declare_executable_product(mkswap)
JLLWrappers.@declare_executable_product(mount)
JLLWrappers.@declare_executable_product(mountpoint)
JLLWrappers.@declare_executable_product(namei)
JLLWrappers.@declare_executable_product(nologin)
JLLWrappers.@declare_executable_product(nsenter)
JLLWrappers.@declare_executable_product(partx)
JLLWrappers.@declare_executable_product(pivot_root)
JLLWrappers.@declare_executable_product(prlimit)
JLLWrappers.@declare_executable_product(raw)
JLLWrappers.@declare_executable_product(readprofile)
JLLWrappers.@declare_executable_product(rename_bin)
JLLWrappers.@declare_executable_product(renice)
JLLWrappers.@declare_executable_product(resizepart)
JLLWrappers.@declare_executable_product(rev)
JLLWrappers.@declare_executable_product(rfkill)
JLLWrappers.@declare_executable_product(rtcwake)
JLLWrappers.@declare_executable_product(script)
JLLWrappers.@declare_executable_product(scriptlive)
JLLWrappers.@declare_executable_product(scriptreplay)
JLLWrappers.@declare_executable_product(setarch)
JLLWrappers.@declare_executable_product(setpgid)
JLLWrappers.@declare_executable_product(setsid)
JLLWrappers.@declare_executable_product(sfdisk)
JLLWrappers.@declare_executable_product(sulogin)
JLLWrappers.@declare_executable_product(swaplabel)
JLLWrappers.@declare_executable_product(swapoff)
JLLWrappers.@declare_executable_product(swapon)
JLLWrappers.@declare_executable_product(switch_root)
JLLWrappers.@declare_executable_product(taskset)
JLLWrappers.@declare_executable_product(umount)
JLLWrappers.@declare_executable_product(unshare)
JLLWrappers.@declare_executable_product(utmpdump)
JLLWrappers.@declare_executable_product(uuidd)
JLLWrappers.@declare_executable_product(uuidgen)
JLLWrappers.@declare_executable_product(uuidparse)
JLLWrappers.@declare_executable_product(wall)
JLLWrappers.@declare_executable_product(wdctl)
JLLWrappers.@declare_executable_product(whereis)
JLLWrappers.@declare_executable_product(wipefs)
JLLWrappers.@declare_executable_product(zramctl)
function __init__()
    JLLWrappers.@generate_init_header(SQLite_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libblkid,
        "lib/libblkid.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfdisk,
        "lib/libfdisk.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblastlog2,
        "lib/liblastlog2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmount,
        "lib/libmount.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsmartcols,
        "lib/libsmartcols.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libuuid,
        "lib/libuuid.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        addpart,
        "sbin/addpart",
    )

    JLLWrappers.@init_executable_product(
        agetty,
        "sbin/agetty",
    )

    JLLWrappers.@init_executable_product(
        blkdiscard,
        "sbin/blkdiscard",
    )

    JLLWrappers.@init_executable_product(
        blkid,
        "sbin/blkid",
    )

    JLLWrappers.@init_executable_product(
        blkzone,
        "sbin/blkzone",
    )

    JLLWrappers.@init_executable_product(
        blockdev,
        "sbin/blockdev",
    )

    JLLWrappers.@init_executable_product(
        cal,
        "bin/cal",
    )

    JLLWrappers.@init_executable_product(
        chcpu,
        "sbin/chcpu",
    )

    JLLWrappers.@init_executable_product(
        chmem,
        "bin/chmem",
    )

    JLLWrappers.@init_executable_product(
        choom,
        "bin/choom",
    )

    JLLWrappers.@init_executable_product(
        chrt,
        "bin/chrt",
    )

    JLLWrappers.@init_executable_product(
        colcrt,
        "bin/colcrt",
    )

    JLLWrappers.@init_executable_product(
        colrm,
        "bin/colrm",
    )

    JLLWrappers.@init_executable_product(
        column,
        "bin/column",
    )

    JLLWrappers.@init_executable_product(
        ctrlaltdel,
        "sbin/ctrlaltdel",
    )

    JLLWrappers.@init_executable_product(
        delpart,
        "sbin/delpart",
    )

    JLLWrappers.@init_executable_product(
        dmesg,
        "bin/dmesg",
    )

    JLLWrappers.@init_executable_product(
        eject,
        "bin/eject",
    )

    JLLWrappers.@init_executable_product(
        enosys,
        "bin/enosys",
    )

    JLLWrappers.@init_executable_product(
        exch,
        "bin/exch",
    )

    JLLWrappers.@init_executable_product(
        fallocate,
        "bin/fallocate",
    )

    JLLWrappers.@init_executable_product(
        fdformat,
        "sbin/fdformat",
    )

    JLLWrappers.@init_executable_product(
        fdisk,
        "sbin/fdisk",
    )

    JLLWrappers.@init_executable_product(
        fincore,
        "bin/fincore",
    )

    JLLWrappers.@init_executable_product(
        findfs,
        "sbin/findfs",
    )

    JLLWrappers.@init_executable_product(
        findmnt,
        "bin/findmnt",
    )

    JLLWrappers.@init_executable_product(
        flock,
        "bin/flock",
    )

    JLLWrappers.@init_executable_product(
        fsck,
        "sbin/fsck",
    )

    JLLWrappers.@init_executable_product(
        fsck_cramfs,
        "sbin/fsck.cramfs",
    )

    JLLWrappers.@init_executable_product(
        fsck_minix,
        "sbin/fsck.minix",
    )

    JLLWrappers.@init_executable_product(
        fsfreeze,
        "sbin/fsfreeze",
    )

    JLLWrappers.@init_executable_product(
        fstrim,
        "sbin/fstrim",
    )

    JLLWrappers.@init_executable_product(
        getopt,
        "bin/getopt",
    )

    JLLWrappers.@init_executable_product(
        hardlink,
        "bin/hardlink",
    )

    JLLWrappers.@init_executable_product(
        hexdump,
        "bin/hexdump",
    )

    JLLWrappers.@init_executable_product(
        hwclock,
        "sbin/hwclock",
    )

    JLLWrappers.@init_executable_product(
        ionice,
        "bin/ionice",
    )

    JLLWrappers.@init_executable_product(
        ipcmk,
        "bin/ipcmk",
    )

    JLLWrappers.@init_executable_product(
        ipcrm,
        "bin/ipcrm",
    )

    JLLWrappers.@init_executable_product(
        ipcs,
        "bin/ipcs",
    )

    JLLWrappers.@init_executable_product(
        isosize,
        "bin/isosize",
    )

    JLLWrappers.@init_executable_product(
        kill_bin,
        "bin/kill",
    )

    JLLWrappers.@init_executable_product(
        last_bin,
        "bin/last",
    )

    JLLWrappers.@init_executable_product(
        lastlog2,
        "bin/lastlog2",
    )

    JLLWrappers.@init_executable_product(
        ldattach,
        "sbin/ldattach",
    )

    JLLWrappers.@init_executable_product(
        logger,
        "bin/logger",
    )

    JLLWrappers.@init_executable_product(
        look,
        "bin/look",
    )

    JLLWrappers.@init_executable_product(
        losetup,
        "sbin/losetup",
    )

    JLLWrappers.@init_executable_product(
        lsblk,
        "bin/lsblk",
    )

    JLLWrappers.@init_executable_product(
        lsclocks,
        "bin/lsclocks",
    )

    JLLWrappers.@init_executable_product(
        lscpu,
        "bin/lscpu",
    )

    JLLWrappers.@init_executable_product(
        lsipc,
        "bin/lsipc",
    )

    JLLWrappers.@init_executable_product(
        lslocks,
        "bin/lslocks",
    )

    JLLWrappers.@init_executable_product(
        lslogins,
        "bin/lslogins",
    )

    JLLWrappers.@init_executable_product(
        lsmem,
        "bin/lsmem",
    )

    JLLWrappers.@init_executable_product(
        lsns,
        "bin/lsns",
    )

    JLLWrappers.@init_executable_product(
        mcookie,
        "bin/mcookie",
    )

    JLLWrappers.@init_executable_product(
        mesg,
        "bin/mesg",
    )

    JLLWrappers.@init_executable_product(
        mkfs,
        "sbin/mkfs",
    )

    JLLWrappers.@init_executable_product(
        mkfs_bfs,
        "sbin/mkfs.bfs",
    )

    JLLWrappers.@init_executable_product(
        mkfs_cramfs,
        "sbin/mkfs.cramfs",
    )

    JLLWrappers.@init_executable_product(
        mkfs_minix,
        "sbin/mkfs.minix",
    )

    JLLWrappers.@init_executable_product(
        mkswap,
        "sbin/mkswap",
    )

    JLLWrappers.@init_executable_product(
        mount,
        "bin/mount",
    )

    JLLWrappers.@init_executable_product(
        mountpoint,
        "bin/mountpoint",
    )

    JLLWrappers.@init_executable_product(
        namei,
        "bin/namei",
    )

    JLLWrappers.@init_executable_product(
        nologin,
        "sbin/nologin",
    )

    JLLWrappers.@init_executable_product(
        nsenter,
        "bin/nsenter",
    )

    JLLWrappers.@init_executable_product(
        partx,
        "sbin/partx",
    )

    JLLWrappers.@init_executable_product(
        pivot_root,
        "sbin/pivot_root",
    )

    JLLWrappers.@init_executable_product(
        prlimit,
        "bin/prlimit",
    )

    JLLWrappers.@init_executable_product(
        raw,
        "sbin/raw",
    )

    JLLWrappers.@init_executable_product(
        readprofile,
        "sbin/readprofile",
    )

    JLLWrappers.@init_executable_product(
        rename_bin,
        "bin/rename",
    )

    JLLWrappers.@init_executable_product(
        renice,
        "bin/renice",
    )

    JLLWrappers.@init_executable_product(
        resizepart,
        "sbin/resizepart",
    )

    JLLWrappers.@init_executable_product(
        rev,
        "bin/rev",
    )

    JLLWrappers.@init_executable_product(
        rfkill,
        "sbin/rfkill",
    )

    JLLWrappers.@init_executable_product(
        rtcwake,
        "sbin/rtcwake",
    )

    JLLWrappers.@init_executable_product(
        script,
        "bin/script",
    )

    JLLWrappers.@init_executable_product(
        scriptlive,
        "bin/scriptlive",
    )

    JLLWrappers.@init_executable_product(
        scriptreplay,
        "bin/scriptreplay",
    )

    JLLWrappers.@init_executable_product(
        setarch,
        "bin/setarch",
    )

    JLLWrappers.@init_executable_product(
        setpgid,
        "bin/setpgid",
    )

    JLLWrappers.@init_executable_product(
        setsid,
        "bin/setsid",
    )

    JLLWrappers.@init_executable_product(
        sfdisk,
        "sbin/sfdisk",
    )

    JLLWrappers.@init_executable_product(
        sulogin,
        "sbin/sulogin",
    )

    JLLWrappers.@init_executable_product(
        swaplabel,
        "sbin/swaplabel",
    )

    JLLWrappers.@init_executable_product(
        swapoff,
        "sbin/swapoff",
    )

    JLLWrappers.@init_executable_product(
        swapon,
        "sbin/swapon",
    )

    JLLWrappers.@init_executable_product(
        switch_root,
        "sbin/switch_root",
    )

    JLLWrappers.@init_executable_product(
        taskset,
        "bin/taskset",
    )

    JLLWrappers.@init_executable_product(
        umount,
        "bin/umount",
    )

    JLLWrappers.@init_executable_product(
        unshare,
        "bin/unshare",
    )

    JLLWrappers.@init_executable_product(
        utmpdump,
        "bin/utmpdump",
    )

    JLLWrappers.@init_executable_product(
        uuidd,
        "sbin/uuidd",
    )

    JLLWrappers.@init_executable_product(
        uuidgen,
        "bin/uuidgen",
    )

    JLLWrappers.@init_executable_product(
        uuidparse,
        "bin/uuidparse",
    )

    JLLWrappers.@init_executable_product(
        wall,
        "bin/wall",
    )

    JLLWrappers.@init_executable_product(
        wdctl,
        "bin/wdctl",
    )

    JLLWrappers.@init_executable_product(
        whereis,
        "bin/whereis",
    )

    JLLWrappers.@init_executable_product(
        wipefs,
        "sbin/wipefs",
    )

    JLLWrappers.@init_executable_product(
        zramctl,
        "sbin/zramctl",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
